### ISSUE TITLE
Invalid or unexpected token SyntaxError with commas inside annotations

### ISSUE THREAD

**Issue by stefanbates** [congajs/conga-annotations#8]
If I have an annotation with commas within the quoted string I get a SyntaxError (stack below). This happens in both 1.0.0 & 1.0.1.

```
SyntaxError: Invalid or unexpected token
    at Object.exports.runInContext (vm.js:66:16)
    at AttributeParser.<anonymous> (d:\Glass\GLASS-vc12-trunk\test\cucumber\doc\node_modules\@conga\annotations\lib\attribute-parser.js:165:14)
    at Array.forEach (native)
    at AttributeParser.parse (d:\Glass\GLASS-vc12-trunk\test\cucumber\doc\node_modules\@conga\annotations\lib\attribute-parser.js:124:11)
    at Reader.parseAnnotations (d:\Glass\GLASS-vc12-trunk\test\cucumber\doc\node_modules\@conga\annotations\lib\reader.js:260:45)
    at Reader.parseMethodAnnotations (d:\Glass\GLASS-vc12-trunk\test\cucumber\doc\node_modules\@conga\annotations\lib\reader.js:131:17)
    at Reader.<anonymous> (d:\Glass\GLASS-vc12-trunk\test\cucumber\doc\node_modules\@conga\annotations\lib\reader.js:81:39)

    at Array.forEach (native)
    at Reader.parse (d:\Glass\GLASS-vc12-trunk\test\cucumber\doc\node_modules\@conga\annotations\lib\reader.js:80:15)
    at parseStepDefinition (d:\Glass\GLASS-vc12-trunk\test\cucumber\doc\parser.js:219:9)
```

**Comment by lampjunkie** [comment]
Hi Stefan, can you provide an example of what the annotation looks like when it causes this error?

**Comment by stefanbates** [comment]
Sure. The simplest would be:

`@CukeThenStep(",")`

My annotation code is quite short:

```
const Annotation = require('@conga/annotations').Annotation;

module.exports = class CukeThenStep extends Annotation {

    /**
     * The possible targets
     *
     * (Annotation.DEFINITION, Annotation.CONSTRUCTOR, Annotation.PROPERTY, Annotation.METHOD)
     *
     * @type {Array}
     */
    static get targets() { return [Annotation.METHOD] }

    /**
     * Constructor to add attributes
     * @type {Array}
     */
    constructor(data, filePath){
      super(data, filePath)        
    }
   
};
```

**Comment by lampjunkie** [comment]
Thanks for the example. Go ahead and install v1.0.2 and let me know if that resolves your issue.

**Comment by stefanbates** [comment]
Yes, that solves the issue. Many thanks. Much appreciated.

**Comment by lampjunkie** [comment]
Great! No problem and thanks for discovering that.
